feat(Navbar): add mapping buttons function to navbar
mariampolski/Gratiana pull request #3
Opened 2024-02-04 19:23 UTC by mariampolski

2024-02-06 04:11 UTC, rackowsky commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
If you want to add font by Google, you should better add this by plugin Fontsource (https://fontsource.org/docs/getting-started/install).

2024-02-06 04:14 UTC, rackowsky commented on src/components/navbar/index.jsx
> +    navbarButtonsList,
It's a mistake. All JSX elements must begin with a capital letter.

2024-02-06 04:15 UTC, rackowsky commented on src/components/navbar/index.style.jsx
> +]
It should go to the normal file, not .style. Style postfix is reserved ONLY for stylization!

2024-02-06 04:22 UTC, rackowsky commented on src/components/navbar/index.style.jsx
> +]
You should make it more clever.
e.g.:
```
export const navbarButtonsList = [
    {
        id: 1,
        name: "Home",
        link: "/home",
        icon: home_icon,
    },
]
```
More context: [My navbar component from another project](https://github.com/rackowsky/my-hobby-blog/blob/main/src/components/navbar/index.js)

2024-02-06 04:28 UTC, rackowsky commented on src/pages/index.jsx
> +        </IndexPageWrapper>
You should use the `Layout` component with `props.children` inside (or with destructuralization - `const Layout = (props) => {}`).

2024-02-06 04:36 UTC, rackowsky requested changes
In general, everything is perfect but I have a few advice.

2024-02-06 04:37 UTC, rackowsky commented
I'll solve it in next commit.

2024-02-06 05:00 UTC, rackowsky commented on src/pages/index.style.jsx
> +    max-width: 1920px;
You don't have to use it, because the body already has a width lock.

2024-02-06 05:04 UTC, rackowsky commented on src/templates/index/hero/index.style.jsx
> +    max-width: 1440px;
Useless because the body already has a width lock. I know that Figma's file has design only up to 1440px but let's make it up to 1920px already, as the lock is set on the body.

2024-02-06 05:11 UTC, rackowsky commented on src/components/navbar/index.style.jsx
> +    font-family: ${theme.typography.navbar.buttons.fontFamily};
Don't use font-family for each element. Font-family is already declared in the `globalStyles.jsx` file. You can use font-family declaration once if you need another font.

2024-02-06 05:47 UTC, merged

2024-02-06 21:01 UTC, mariampolski commented on src/pages/index.jsx
> +        </IndexPageWrapper>
I didn't understand what exactly you mean, could you elaborate?

2024-02-06 21:06 UTC, mariampolski commented on src/templates/index/hero/index.style.jsx
> +    max-width: 1440px;
Should I extend page width to have scale to 1920px?

2024-02-07 05:45 UTC, rackowsky commented on src/pages/index.jsx
> +        </IndexPageWrapper>
> I didn't understand what exactly you mean, could you elaborate?

In the latest commit, you have explanation (/components/layout). The `layout` component is more universal than creating a wrapper for the entire page each time.

![image](https://github.com/mariampolski/Gratiana/assets/73818700/24cb0786-b9bc-4004-8c9e-73d967edec7f)

2024-02-07 05:47 UTC, rackowsky commented on src/templates/index/hero/index.style.jsx
> +    max-width: 1440px;
> Should I extend page width to have scale to 1920px?

The page is already scaling to 1920px, look inside the `globalStyles.jsx` file.

![image](https://github.com/mariampolski/Gratiana/assets/73818700/4ed46734-1aa9-4804-a139-813f4111ef46)